feat: delete archive
depromeet/Archive_Backend pull request #37
Opened 2021-11-15 12:36 UTC by kiteB

delete 요청이 들어오면 is_deleted 변수를 True로 변경하도록 구현하였습니다.

2021-11-16 14:15 UTC, KimDoubleB requested changes

2021-11-16 14:15 UTC, KimDoubleB commented on src/main/java/com/depromeet/archive/api/ArchiveController.java
> +
로직과는 상관없지만 이런 곳에 쓸모없는 공백이 너무 많은 것 같습니다.
- 구분을 두기 위해 한 라인 정도만 있어도 될 것 같네요.

가끔 reformat 하다보면 이런 것도 수정사항으로 반영되서 커밋할 때 다 빼줘야하더라구요🥲
커밋하시기 전에 code reformat 해보고 커밋해주셨으면 좋겠습니다.
- ref: https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2021-11-16 14:45 UTC, kiteB commented on src/main/java/com/depromeet/archive/api/ArchiveController.java
> +
넵 죄송합니다😭 앞으로 주의하겠습니다!!

2021-11-18 14:03 UTC, KimDoubleB approved these changes

2021-11-18 14:03 UTC, merged